name: Update gist with WakaTime stats
on:
  schedule:
    # 00:00 UTC <==> 08:00(next day) GMT +08:00
    # 16:00 UTC <==> 00:00(next day) GMT +08:00
    - cron: "*/4 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: fangbinwei/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: fd7b41abbe59374758ef94cb94322c5d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
